language: bash
services:
- docker
before_script:
- if [ -n "$DOCKER_USERNAME" ]; the echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
script:
- make image flavor=$FLAVOR nginx_version=$NGINX_VERSION
- if [ -n "$DOCKER_USERNAME" ]; then docker push tsuru/nginx-$FLAVOR:$NGINX_VERSION; fi
env:
  global:
  - secure: INyCcvgvdpFFv3r4AxGINYduePHcz99WilzjD+Rv8iUFyJdir8ouG2mcLOp1jn3rosx33bter/Q7G5S8zCoBsm0JY1WcRnuWpOzeb8b1j6v20ghW81+1chMiJGcuCERVJA4z2C/4yJWaf4LqTHXZGGyx6nSMusCKvXzxEBlAidNsRC3piS4eR09Vb4mm3G16t+NGgCmWtuhe+aCaI/bYUU6rAtxQ193xhLCv/m6J0QISPLy+Ev7Yx8erS0FsTyIBKF5m+aXvkZLTKcjwBYKJ4ttarSuXjgzEJkXN8cx30oNnqPbAlqlLH6rF7hbTvVBczvsHbklkYbjvTxIkI90XD+sT1Xj/BUpzuHI3gjuv3RDpR+0IiryRWk23DL8r1eLqVmOvnmKF/p1ItvxZCM1qMK/oMp4MDrM8LfIYf4OkU2hZPTk02Jp62w9oBpt/qNN4kuTv+24/5SugCe5kKoeWzMZEhk67T+tTM2DjZDmIlO3Bu8SSGUlUuh4yLVAD/CxDPYxqUoGeixK9QENw0/SQlUr9R+q3NfJrBQpj0nfniW7c2Igd6yth5RXXs0QWvsnv75fQ8sQWEwV3WiRW9YGOKHAMxY2OgttO2bc9HECXzvSlSDW7IA4z1kpR9B1XumZgQ5tb9Mtca+IC3uZX7LkZLHkkiFmY0Latf/ZkugCidHQ=
  matrix:
  - FLAVOR=tsuru NGINX_VERSION=1.14.0
  - FLAVOR=tsuru NGINX_VERSION=1.15.0
matrix:
  fast_finish: true
notifications:
  slack:
    rooms:
      secure: GHnLu+xiDqsJf9DaBXjVTsBDomVD3ty/Fsqq7NoMBhYb6M/Asqx68O6qdoch9ZPakaeQZoDvN6RYZrhS8+8+IP8sOEWchglGJpTHA8ivh7b0e8GXVRieAT+0NJsznGSGt+iiWkcMNJsy+zCVPfL8jhqut/2GjZOVra839UG7JqBmFy4UQu/yxgg8sOm9SoyXZ5N6reOIFGRhly2zzVKtVjfvq+jiFRkNoEB0t9eYvKquC6WkbEadJ6vHkGpcpvYjv1WRvSEYGygBTLwBoxTr7ko9zCGRusJ1rtWu+r4iuvQH5g8k9ZZAE3tVtumlaRT/vdMlLk2FQEUqfC41ZudUp5gkKRosw00YnVsg5ItcPtuPU11UVGLTvBvAlRh2EhiGicWo8fwszfiqt0lAMEGtRJbdAFZTU86UfKsgURHfByOpzlGnOB+Q/SFYJrFdYqvABgNNOYmeNy5pbVooHHVyPpRo4xR8+yMKinYzbN7g6LbU+Msh7ecWe3hQWGFWBpz8gCOL7IxgIhLIzovNDTFvdw7RXncTtDloqJ+CWt5VnxBlcs381B2tAUlt4uqpqTC4jraVxIRHqKYCH37/r9xojXzUv0peB3CAre1Y164aA38U5S5hN3ylyD66o5kbWF8Eyz5k9tF6bEdYdVibgn/FHwM6sJjKUu+GMviQXq1P7Kc=
